version: '3.8'

services:
  api-scraper:
    build: .
    volumes:
      - ./scraped_data:/app/scraped_data
    environment:
      - TZ=UTC
    restart: "no"
    # Add resource limits to be good citizens
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M 